name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    name: Security Scan
    uses: ./.github/actions/security/checkov.yaml

  tfsec-scan:
    name: TFSec Scan
    uses: ./.github/actions/security/tfsec.yaml
    with:
      WORKING_DIRECTORY: ./terraform

  terraform-plan:
    name: Terraform Plan
    needs: [security-scan, tfsec-scan]
    uses: ./.github/actions/terraform/terraform-plan.yaml
    with:
      TERRAFORM_VERSION: ~1.12
      WORKING_DIRECTORY: ./terraform
    secrets:
      TF_PVE_PROVIDER_ENDPOINT: ${{ secrets.TF_PVE_PROVIDER_ENDPOINT }}
      TF_PVE_PROVIDER_API_TOKEN: ${{ secrets.TF_PVE_PROVIDER_API_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ENDPOINT_URL_S3: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
